sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8

install:
  - npm install

deploy:
  provider: npm
  email: tquilamobile@tquilaanz.com
  api_key: $NPM_TOKEN

script:
  - npm run build
  - rm -rf .git
  - npm run buildNPM
