sudo: false
language: node_js
node_js:
  - "stable"
cache:
  directories:
    - node_modules
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
deploy:
  provider: npm
  email: "tquilamobile@tquilaanz.com"
  api_key: "e11d3226-cc60-4039-967d-34a1853a2b1e"

install:
  - npm install

script:
  - npm run build
  - npm run buildNPM
  - npm test
